# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b686279353414767854d98a9dbd620a4503e541abfc86fedd5912b0da4d8f24d7efcf25d1f925e7b4cb7dc8a8780f5a6b2b91682dd218cde66d5f987b1e48a61

test:
  secret_key_base: d2cc77ab8b29c7a2307e2f95e09b00188c342cffb7131f75e2b5c33e9b43e9f85a5c63bcb0c50fee4d76b8642c37b0363d158b0f223244f4e2e5c417435908f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
